### PR TITLE
fix: update z-index of various components (#766)

### PR DESCRIPTION
**Pull request by bredy**
- with recent changes on full screen in incident-manager we need to adjust library z-indexes to have space for full screen

**Please check if the PR fulfills these requirements**
- [x] The commit message follows semantic commit message guidelines
- [x] The changes are documented in component docs and changelog
- [x] The ESLint plugin has been updated if a new component is added
- [x] Test have been added or modified, if appropriate
- [x] Has been verified locally
- [x] The component should accept a class name as a prop, if appropriate
- [x] The component should accept a forward ref, if appropriate

**What kind of change does this PR introduce?**
Supports #766

**What is the new behavior (if this is a feature change)?**
`ADialog`, `AMenuBase` and `APageOveraly` `z-index` was changed. Now there is sufficient space in components `z-index`es to show full screen properly.

**Does this PR introduce a breaking change?** 
Yes, this pull request (PR) has the potential to cause issues. The "z-index" has been modified for some components, and if any custom components have manually set "z-index" values, it could disrupt the intended layering between them.

### CODE REVIEW

**Comment by rwharrisjr** [comment]
@trent-boyd @brennarvo @sabrinamokerji Thoughts on multiplying the new numbers by 1000 to allow some space for dev overrides if needed?

**Comment by trent-boyd** [comment]
@rwharrisjr Yeah, x1000 sounds good.

**Comment by sabrinamokerji** [comment]
@rwharrisjr I'm good with that

**Comment by bredy** [comment]
Guys I update it x100, I think it provides sufficient space for developers.

**Comment by rwharrisjr** [comment]
That seems like a reasonable margin

**Review by rwharrisjr — APPROVED** [review]

**Pull request merged**
