### PR TITLE
fix ATextInput layout example

### PR DESCRIPTION
**Pull request by rrubas**

### CODE REVIEW

**Comment by rrubas** [comment]
Screenshot 2023-03-02 at 11 37 50
Screenshot 2023-03-02 at 11 39 04

**Comment by rrubas** [comment]
Screenshot 2023-03-02 at 11 38 16
Screenshot 2023-03-02 at 11 39 26

**Comment by mvelkCisco** [comment]
Makes examples look better with #223. It's the best when input components don't have hardcoded margins for higher flexibility. So the apps should use some kind of layout components when there's more inputs close to each other to create correct spacing. These examples also provide more guidance.

**Review by mvelkCisco — APPROVED** [review]

**Review by rwharrisjr — APPROVED** [review]
nice!

**Pull request merged**
