### PR TITLE
#152 - fix border radius for first and last menu item

### LINKED ISSUE #152: Slight whitespace on border-radius gap
Slight whitespace on menu items on hover
Screenshot 2023-02-06 at 10 03 59 AM

### PR DESCRIPTION
**Pull request by rwharrisjr**
Resolves #152 

Note that this breaks the example with custom styling for border radius on the menu, but does fix the default rounded border case.

See "More Menu" button on the Storybook

### CODE REVIEW

**Review by brennarvo — COMMENTED** [review]
Another option is to add `overflow: hidden` to the menu container and remove the `border-radius` entirely from the menu items so that their corners are covered by the parent menu's container. My only worry is that maybe there are some instances out there right now where content *is* actually overflowing the menu on purpose?

**Comment by rwharrisjr** [comment]
I can't think of a use case for intentionally overflowing the menu. I think adjusting the border radius guarantees non breaking, even though I like your solution better.

**Comment by androche** [comment]
I like pictures :)

**Comment by rwharrisjr** [comment]
Before

Screenshot 2023-02-09 at 1 55 50 PM


After
Screenshot 2023-02-09 at 1 55 22 PM

**Review by androche — APPROVED** [review]

**Pull request merged**
