### PR TITLE
Use theme icon colors rather than currentColor

### PR DESCRIPTION
**Pull request by rwharrisjr**
@mvelkCisco pointed out that use of `currentColor` as the default doesn't line up with the magnetic designs. This was a carryover from the original atomic-react repo. 

This PR changes to use the theme mapped colors. Preview deployment for validation https://magna-react-git-icon-colors.securex-preview.app/components/icon

-----------

Also adding "kebab helper" so that most uses of camelCase icon names should continue to work 

Screenshot 2023-03-02 at 4 43 27 PM

### CODE REVIEW

**Comment by mvelkCisco** [comment]
You are right that going forward this change will make us avoid more issues than it could introduce now. However id does break icon button:
https://magna-react-git-icon-colors.securex-preview.app/components/button#install
image

Including hover states. Those might need som kind of override.

**Comment by mvelkCisco** [comment]
Tags before:
image

After:
image

**Comment by mvelkCisco** [comment]
I quickly scanned the rest of the framework and I think fixing the `AButton` including the hover/focus colors, and the tags, should address all the regressions.

It might still break apps that relied on the original behavior, but I would still do the change.

**Comment by rwharrisjr** [comment]
Fixed button and tag specific icons. 

Also added negative status fill for `critical-stop`. This was not colored correctly in the original atomic-react.

**Comment by mvelkCisco** [comment]
This icon looks broken after the latest change https://magna-react-git-icon-colors.securex-preview.app/components/popover
image

**Comment by rwharrisjr** [comment]
Good catch, had lost specificity on stroke unset for the legacy atomic icons.

**Review by brennarvo — APPROVED** [review]

**Pull request merged**
