### PR TITLE
Remove deprecated properties and features

### PR DESCRIPTION
**Pull request by rwharrisjr**
# DEPRECATION REMOVALS

### AApp 

- Atomic colors removed

### AAutoComplete

- remove `hint` property. Use `hints` instead

### AButtonGroup

- removed `hint` property. Use `hints` instead

### ACombobox 

- removed `hint` property. Use `hints` instead

### ADialog (removed)

- Component removed
- Use `AModal`

### ADrawer

- removed `closeBtnOnClick` property
- removed `closeTitle` property
- removed `closeBtnProps` property
- use `onClose` as the callback for close actions

### AFieldBase

- removed `hint` property.
- removed `hintUsesValidationState` property
- removed  `hideHintOnError` property
- Use `hints` property instead

### AInputBase 

- removed `hint` property
- Use `hints` property instead

### ADotLoader

- removed component

### APageLoader

- removed component

### ALoader

- removed `dot` varient

### ALoadNotification

- removed component (was not documented)
- Use AEmptyState

### AModal

- removed `onClickOutside` property
- Use `onClose` instead

### AMultiSelect

- removed `hint` property. Use `hints` instead

### ASelect

- removed `hint` property. Use `hints` instead

### ASlider

- removed `hint` property. Use `hints` instead

### ATag

- removed `count` property. No longer needed
- removed `level` property. Handled by `status` and `binary`

### ATextarea

- removed `hint` property. Use `hints` instead

### ATextInput

- removed `hint` property. Use `hints` instead

### SCSS

- removed `map-deep-merge` in functions.scss

-----

# Migration Notes

- The `hint` property can be safely replaced with `hints` and no other changes
- Drawers and modals will need to migrate from `onCloseBtnClick` to `onClose`
- `ALoadNotification` should be replaced with `AEmptyState`
- `ADialog` should be replaced with `AModal`

### CODE REVIEW

**Comment by androche** [comment]
While were here let's delete the palette file and the themeMap: https://github.com/cisco-sbg-ui/magna-react/issues/617

**Comment by rwharrisjr** [comment]
Probably best to remove/trim the palette down in another PR. There are a lot of impacts with the generated classes from https://github.com/cisco-sbg-ui/magna-react/blob/canary/framework/components/AApp/base/color-helpers.scss#L15

**Comment by androche** [comment]
Oh ok, well themes folder is safe to delete completely.

**Comment by androche** [comment]
removed closeBtnOnClick property
removed closeTitle property
removed closeBtnProps property
use onClose as the callback for close actions

Will all drawers have a close button now? The library should still provide a built in close button.

**Comment by rwharrisjr** [comment]
@androche ADrawerTitle gets the `onClose` callback from the drawer context, and that will automatically add a close button

**Review by androche — CHANGES_REQUESTED** [review]
It looks like `hint` needs to be replaced by `hints` in the mdx examples.  Also, there is a size difference between using hints as an array, and hints as a string

Screenshot 2024-04-16 at 9 18 47 AM

Screenshot 2024-04-16 at 9 18 27 AM

**Review by androche — APPROVED** [review]
🎉  Bit o' spring cleaning

**Pull request merged**
