### PR TITLE
Add prop passing for tooltips on inline edits

### LINKED ISSUE #563: Add maxWidth prop to tooltip and tooltipProps for AInlineText
Need to add ability to control width and positioning when utilizing the `showTooltip` prop in a-inline editors
Screenshot 2023-11-07 at 11 30 33 AM

### PR DESCRIPTION
**Pull request by rwharrisjr**
Resolves #563

### CODE REVIEW

**Review by androche — COMMENTED** [review]
I might be totally nuts, but I don't see `AInlineInputBase` in the sidebar to view it in the playground.  Is it named something else? 

Screenshot 2023-11-14 at 9 29 27 AM

**Comment by rwharrisjr** [comment]
/extend/inline-input

https://github.com/cisco-sbg-ui/magna-react/blob/canary/framework/components/AInlineInputBase/AInlineInputBase.mdx#L3

**Comment by androche** [comment]
Is there a link? I still cant access that route.

**Comment by rwharrisjr** [comment]
https://magna-react.vercel.app/extend/inline-input

**Comment by androche** [comment]
Thanks looks good, although this was here before some large spacing in our inputs. Looks like its taking up the input line-height.  Should we just change that to a min-height or target a smaller line height on the text?

Screenshot 2023-11-14 at 9 53 40 AM
Screenshot 2023-11-14 at 9 54 41 AM

**Comment by rwharrisjr** [comment]
Replaced with corresponding line-height vars

**Review by androche — APPROVED** [review]

**Pull request merged**
